// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"strings"
	"time"

	"github.com/cloudwego/biz-demo/gomall/app/frontend/biz/router"
	"github.com/cloudwego/biz-demo/gomall/app/frontend/conf"
	"github.com/cloudwego/biz-demo/gomall/app/frontend/infra/rpc"
	"github.com/cloudwego/biz-demo/gomall/app/frontend/middleware"
	frontendutils "github.com/cloudwego/biz-demo/gomall/app/frontend/utils"
	"github.com/cloudwego/biz-demo/gomall/common/mtl"
	commonutils "github.com/cloudwego/biz-demo/gomall/common/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	hertzobslogus "github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
	hertzoteltracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"github.com/joho/godotenv"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

var (
	ServiceName  = frontendutils.ServiceName
	MetricsPort  = conf.GetConf().Hertz.MetricsPort
	RegistryAddr = conf.GetConf().Hertz.RegistryAddress
)

func main() {
	_ = godotenv.Load()
	// init dal
	// dal.Init()
	MetricsAddress := MetricsPort
	if strings.HasPrefix(MetricsAddress, ":") {
		localIp := commonutils.MustGetLocalIPv4()
		MetricsAddress = localIp + MetricsAddress
	}
	consul, registryInfo := mtl.InitMetric(ServiceName, MetricsAddress, RegistryAddr)
	defer consul.Register(registryInfo)

	p := mtl.InitTracing(ServiceName)
	defer p.Shutdown(context.Background())

	rpc.Init()

	address := conf.GetConf().Hertz.Address

	// NewServerTracer 创建并初始化一个服务器追踪器。
	// 该函数没有输入参数。
	// 返回值有两个：
	// 1. tracer 是一个用于追踪请求的服务器追踪器实例。
	// 2. cfg 包含了服务器追踪器的配置信息。
	tracer, cfg := hertzoteltracing.NewServerTracer()

	h := server.New(server.WithHostPorts(address), server.WithTracer(
		prometheus.NewServerTracer(
			"",
			"",
			prometheus.WithRegistry(mtl.Registry),
			prometheus.WithDisableServer(true),
		),
	), tracer)
	h.Use(hertzoteltracing.ServerMiddleware(cfg))
	registerMiddleware(h)

	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	router.GeneratedRegister(h)
	h.LoadHTMLGlob("template/*")
	// h.Delims("{{", "}}") // 自定义模板标签
	h.Static("/static", "./")

	h.GET("/sign-in", func(c context.Context, ctx *app.RequestContext) {
		// ctx.HTML(consts.StatusOK, "sign-in.tmpl", utils.H{"Title": "sign-in"}) //找文件
		data := utils.H{
			"Title": "sign-in",
			"Next":  ctx.Query("next"), //上一个页面,使登录后回到之前的界面
		}
		ctx.HTML(consts.StatusOK, "sign-in", data) //找到模板
	})
	h.GET("/sign-up", func(c context.Context, ctx *app.RequestContext) {
		// ctx.HTML(consts.StatusOK, "sign-in.tmpl", utils.H{"Title": "sign-in"}) //找文件
		ctx.HTML(consts.StatusOK, "sign-up", utils.H{"Title": "sign-up"}) //找到模板
	})

	h.GET("/about", func(c context.Context, ctx *app.RequestContext) {
		hlog.CtxInfof(c, "CloudWeGo shop about page")
		ctx.HTML(consts.StatusOK, "about", utils.H{"Title": "about"})
	})
	h.Spin()
}

func registerMiddleware(h *server.Hertz) {

	store, _ := redis.NewStore(10, "tcp", conf.GetConf().Redis.Address, "", []byte(os.Getenv("SESSION_SECRET")))
	h.Use(sessions.New("cloudwego-shop", store))
	// log
	logger := hertzobslogus.NewLogger(hertzobslogus.WithLogger(hertzlogrus.NewLogger().Logger()))
	// logger := hertzlogrus.NewLogger()
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	var flushInterval time.Duration
	if os.Getenv("GO_ENV") == "online" {
		flushInterval = time.Minute
	} else {
		flushInterval = time.Second
	}
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: flushInterval,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())

	middleware.RegisterMiddleware(h)
}
